version: "3.8"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
